import type { NextPage } from "next";
import Head from "next/head";

// inspiration: https://pedro-git-v2-peduarte.vercel.app/

const Intro: NextPage = ({ pageProps }: any) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Page Intro</h1>
    </>
  );
};

export default Intro;
